robot_urdf_path: 'robots/ur5e/ur5e.urdf'

joint_upper_bound: [ 6.283,  6.283,  6.283,  6.283,  6.283,  6.283]
joint_lower_bound: [-6.283, -6.283, -6.283, -6.283, -6.283, -6.283]

# link_color: {
#   base_link:        [0.2, 0.2, 0.2, 1.0],
#   shoulder_link:    [0.5, 0.7, 1.0, 1.0],
#   upper_arm_link:   [0.5, 0.7, 1.0, 1.0],
#   forearm_link:     [1.0, 0.42, 0.04, 1.0],
#   wrist_1_link:     [0.5, 0.7, 1.0, 1.0],
#   wrist_2_link:     [0.5, 0.7, 1.0, 1.0],
#   wrist_3_link:     [1.0, 0.42, 0.04, 1.0],
#   tool0:            [0.2, 0.2, 0.2, 1.0]
# }


